version: "3.3"

services:
  graphql:
    depends_on:
      - postgresql-db
    build: ./back-end
    env_file:
      - ./environment/node.env
      - ./environment/postgresql_db.env
    environment:
      - POSTGRESQL_DB_HOST=postgresql-db
    ports:
      - "5000:5000"
    links:
      - postgresql-db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgresql-db:
    build: ./database
    env_file: ./environment/postgresql_db.env
