version: "3.3"

services:
  graphql:
    depends_on:
      - postgresql-db
    image: loert/questionnaire:back-end2
    env_file:
      - ./environment/node.env
      - ./environment/postgresql_db.env
    environment:
      - POSTGRESQL_DB_HOST=postgresql-db
    ports:
      - "5000:5000"
    links:
      - postgresql-db

  postgresql-db:
    image: loert/questionnaire:db1
    environment:
      - PGDATA=/data
    env_file: ./environment/postgresql_db.env
    volumes:
      - data:/data

volumes:
  data:
